import { MapVaultItem, WorkspaceTab } from '../types';
import { DEFAULT_LAYERS_CONFIG } from './defaultSession';

export const BUILTIN_VAULT_PRESETS: MapVaultItem[] = [
  {
    id: 'vault-preset-global-aetheria',
    name: '🗺️ Королевство Этерия (Глобальная карта)',
    category: 'Глобальные миры',
    description: 'Глобальная интерактивная карта мира с установленными порталами в Подземелья, Города, Таверны и Логова чудовищ.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524654458049-e36be0721fa2?w=800&q=80',
    previewColor: '#0ea5e9',
    tags: ['Глобальная', 'Мир', 'Порталы', 'Кампания', 'Регион'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    isBuiltInPreset: true,
    stats: {
      propsCount: 4,
      hasFog: false,
      hasEffects: true,
      hasDrawings: false,
      hasSpells: false,
      bgWidth: 1920,
      bgHeight: 1080,
    },
    tabSnapshot: {
      id: 'tab-global-aetheria',
      name: '🗺️ Королевство Этерия',
      icon: '🗺️',
      color: '#0ea5e9',
      notes: 'Главная стратегическая карта региона. Кликните по маркерам локаций, чтобы открыть их в отдельных вкладках.',
      createdAt: 1700000000000,
      updatedAt: 1700000000000,
      maps: [
        {
          id: 'map-bg-aetheria',
          name: 'Карта Королевства Этерия',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1524654458049-e36be0721fa2?w=1920&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1524654458049-e36be0721fa2?w=600&q=80',
          width: 1920,
          height: 1080,
          aspectRatio: 1920 / 1080,
          position: { x: -960, y: -540 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          hash: 'hash-aetheria-global',
          fileSize: 1024000,
          format: 'jpg',
          category: 'Глобальные миры',
          layer: 'background',
          locked: true,
        },
        {
          id: 'portal-dragon-lair',
          name: 'Вход: Вулканическое Логово Дракона',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
          width: 260,
          height: 170,
          aspectRatio: 260 / 170,
          position: { x: 280, y: -320 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 15,
          opacity: 1,
          hash: 'hash-portal-dragon',
          fileSize: 256000,
          format: 'jpg',
          category: 'Порталы',
          layer: 'props',
          isSubmapPortal: true,
          targetVaultMapId: 'vault-preset-dragon-lair',
          targetVaultMapName: '🏰 Логово Вулканического Дракона',
          targetVaultThumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
          portalBadgeText: 'Логово Босса (Ур. 10-14)',
        },
        {
          id: 'portal-tavern-goblin',
          name: 'Вход: Таверна "Пьяный Гоблин"',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400&q=80',
          width: 260,
          height: 170,
          aspectRatio: 260 / 170,
          position: { x: -450, y: 80 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 15,
          opacity: 1,
          hash: 'hash-portal-tavern',
          fileSize: 256000,
          format: 'jpg',
          category: 'Порталы',
          layer: 'props',
          isSubmapPortal: true,
          targetVaultMapId: 'vault-preset-tavern-goblin',
          targetVaultMapName: '🍺 Таверна "Пьяный Гоблин"',
          targetVaultThumbnailUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80',
          portalBadgeText: 'Городская Таверна',
        },
        {
          id: 'portal-forest-ambush',
          name: 'Вход: Лесная Засада на Тракте',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=400&q=80',
          width: 260,
          height: 170,
          aspectRatio: 260 / 170,
          position: { x: -120, y: -200 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 15,
          opacity: 1,
          hash: 'hash-portal-forest',
          fileSize: 256000,
          format: 'jpg',
          category: 'Порталы',
          layer: 'props',
          isSubmapPortal: true,
          targetVaultMapId: 'vault-preset-forest-ambush',
          targetVaultMapName: '🌲 Лесная Засада на Королевском Тракте',
          targetVaultThumbnailUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
          portalBadgeText: 'Дикая Природа',
        },
        {
          id: 'portal-lich-crypt',
          name: 'Вход: Крипта Древнего Лича',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
          width: 260,
          height: 170,
          aspectRatio: 260 / 170,
          position: { x: -620, y: -380 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 15,
          opacity: 1,
          hash: 'hash-portal-lich',
          fileSize: 256000,
          format: 'jpg',
          category: 'Порталы',
          layer: 'props',
          isSubmapPortal: true,
          targetVaultMapId: 'vault-preset-lich-crypt',
          targetVaultMapName: '💀 Крипта Древнего Лича',
          targetVaultThumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&q=80',
          portalBadgeText: 'Подземелье Лича',
        },
      ],
      activeMapId: 'map-bg-aetheria',
      camera: {
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
        rotation: 0,
        aspectRatio: 16 / 9,
        locked: false,
        zoom: 0.85,
      },
      fog: {
        enabled: false,
        opacity: 0.9,
        style: 'white-mist',
        density: 1,
        animated: false,
        history: [],
      },
      grid: {
        enabled: true,
        type: 'hex',
        size: 70,
        color: '#38bdf8',
        opacity: 0.2,
        offsetX: 0,
        offsetY: 0,
      },
      drawings: [],
      spellTemplates: [],
      animatedEffects: [
        {
          id: 'fx-dragon-flame',
          position: { x: 280, y: -320 },
          radius: 90,
          type: 'fire',
          intensity: 0.8,
          createdAt: Date.now(),
        },
      ],
      layersConfig: DEFAULT_LAYERS_CONFIG,
    },
  },
  {
    id: 'vault-preset-dragon-lair',
    name: '🏰 Логово Вулканического Дракона',
    category: 'Боссы',
    description: 'Опасное подземное логово с кипящей лавой, золотыми сокровищницами, живым пламенем и сундуками.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    previewColor: '#f97316',
    tags: ['Дракон', 'Лава', 'Босс', 'Огонь', 'Сокровища'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    isBuiltInPreset: true,
    stats: {
      propsCount: 3,
      hasFog: true,
      hasEffects: true,
      hasDrawings: false,
      hasSpells: true,
      bgWidth: 1600,
      bgHeight: 1200,
    },
    tabSnapshot: {
      id: 'tab-dragon-lair',
      name: '🏰 Логово Дракона',
      icon: '🐉',
      color: '#f97316',
      notes: 'Вулканический дракон пробуждается при входе в центральную залу. Логово имеет 3 действия логова на инициативе 20.',
      createdAt: 1700000000000,
      updatedAt: 1700000000000,
      maps: [
        {
          id: 'map-bg-dragon',
          name: 'Зал Лавового Трона',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
          width: 1600,
          height: 1200,
          aspectRatio: 1600 / 1200,
          position: { x: -800, y: -600 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          hash: 'hash-dragon-bg',
          fileSize: 1024000,
          format: 'jpg',
          category: 'Боссы',
          layer: 'background',
          locked: true,
        },
        {
          id: 'prop-dragon-chest-1',
          name: 'Древний Сундук с Золотом',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1533158307587-828f0a76ef96?w=400&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1533158307587-828f0a76ef96?w=200&q=80',
          width: 90,
          height: 90,
          aspectRatio: 1,
          position: { x: 220, y: 150 },
          scale: { x: 1, y: 1 },
          rotation: 12,
          zIndex: 12,
          opacity: 1,
          hash: 'hash-chest-1',
          fileSize: 120000,
          format: 'jpg',
          category: 'Пропсы',
          layer: 'props',
        },
      ],
      activeMapId: 'map-bg-dragon',
      camera: {
        x: 0,
        y: 0,
        width: 1200,
        height: 675,
        rotation: 0,
        aspectRatio: 16 / 9,
        locked: false,
        zoom: 1,
      },
      fog: {
        enabled: true,
        opacity: 0.92,
        style: 'red-smoke',
        history: [
          { x: 0, y: 100, radius: 450, type: 'reveal' },
        ],
      },
      grid: {
        enabled: true,
        type: 'square',
        size: 50,
        color: '#f97316',
        opacity: 0.3,
        offsetX: 0,
        offsetY: 0,
      },
      drawings: [],
      spellTemplates: [
        {
          id: 'spell-fire-breath',
          type: 'cone',
          position: { x: 0, y: -100 },
          radius: 300,
          color: '#ef4444',
          label: 'Огненное Дыхание (Конус 60 фт)',
          feetRadius: 60,
          angle: 90,
          effectType: 'fire',
          createdAt: Date.now(),
        },
      ],
      animatedEffects: [
        {
          id: 'fx-lava-pit-1',
          position: { x: -180, y: -120 },
          radius: 140,
          type: 'fire',
          intensity: 1.0,
          createdAt: Date.now(),
        },
        {
          id: 'fx-lava-pit-2',
          position: { x: 240, y: -80 },
          radius: 120,
          type: 'fire',
          intensity: 0.9,
          createdAt: Date.now(),
        },
      ],
      layersConfig: DEFAULT_LAYERS_CONFIG,
    },
  },
  {
    id: 'vault-preset-tavern-goblin',
    name: '🍺 Таверна "Пьяный Гоблин"',
    category: 'Здания',
    description: 'Уютная двухэтажная городская таверна с барной стойкой, камином, деревянными столами и сценой для барда.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80',
    previewColor: '#eab308',
    tags: ['Таверна', 'Город', 'Камин', 'Отдых', 'Здание'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    isBuiltInPreset: true,
    stats: {
      propsCount: 2,
      hasFog: false,
      hasEffects: true,
      hasDrawings: false,
      hasSpells: false,
      bgWidth: 1400,
      bgHeight: 1000,
    },
    tabSnapshot: {
      id: 'tab-tavern-goblin',
      name: '🍺 Таверна "Пьяный Гоблин"',
      icon: '🍺',
      color: '#eab308',
      notes: 'Трактирщик Брок наливает медовуху за 3 мп. В углу сидит таинственный эльф в капюшоне с квестом.',
      createdAt: 1700000000000,
      updatedAt: 1700000000000,
      maps: [
        {
          id: 'map-bg-tavern',
          name: 'Главный Зал Таверны',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1400&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=600&q=80',
          width: 1400,
          height: 1000,
          aspectRatio: 1400 / 1000,
          position: { x: -700, y: -500 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          hash: 'hash-tavern-bg',
          fileSize: 850000,
          format: 'jpg',
          category: 'Здания',
          layer: 'background',
          locked: true,
        },
      ],
      activeMapId: 'map-bg-tavern',
      camera: {
        x: 0,
        y: 0,
        width: 1100,
        height: 618,
        rotation: 0,
        aspectRatio: 16 / 9,
        locked: false,
        zoom: 1,
      },
      fog: {
        enabled: false,
        opacity: 0.9,
        style: 'white-mist',
        density: 1,
        animated: false,
        history: [],
      },
      grid: {
        enabled: true,
        type: 'square',
        size: 50,
        color: '#fef08a',
        opacity: 0.25,
        offsetX: 0,
        offsetY: 0,
      },
      drawings: [],
      spellTemplates: [],
      animatedEffects: [
        {
          id: 'fx-tavern-fireplace',
          position: { x: -240, y: -180 },
          radius: 80,
          type: 'fire',
          intensity: 0.8,
          createdAt: Date.now(),
        },
      ],
      layersConfig: DEFAULT_LAYERS_CONFIG,
    },
  },
  {
    id: 'vault-preset-forest-ambush',
    name: '🌲 Лесная Засада на Королевском Тракте',
    category: 'Природа',
    description: 'Лесная дорога у горной реки с опрокинутой повозкой, густыми деревьями и живой анимированной рекой.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    previewColor: '#22c55e',
    tags: ['Лес', 'Река', 'Засада', 'Природа', 'Дорога'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    isBuiltInPreset: true,
    stats: {
      propsCount: 1,
      hasFog: false,
      hasEffects: true,
      hasDrawings: false,
      hasSpells: false,
      bgWidth: 1600,
      bgHeight: 1000,
    },
    tabSnapshot: {
      id: 'tab-forest-ambush',
      name: '🌲 Лесная Засада',
      icon: '🌲',
      color: '#22c55e',
      notes: 'Бандиты прячутся за валунами на правом берегу реки. Переход вброд требует проверки Атлетики КС 12.',
      createdAt: 1700000000000,
      updatedAt: 1700000000000,
      maps: [
        {
          id: 'map-bg-forest',
          name: 'Королевский Тракт у Реки',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1600&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
          width: 1600,
          height: 1000,
          aspectRatio: 1600 / 1000,
          position: { x: -800, y: -500 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          hash: 'hash-forest-bg',
          fileSize: 920000,
          format: 'jpg',
          category: 'Природа',
          layer: 'background',
          locked: true,
        },
      ],
      activeMapId: 'map-bg-forest',
      camera: {
        x: 0,
        y: 0,
        width: 1200,
        height: 675,
        rotation: 0,
        aspectRatio: 16 / 9,
        locked: false,
        zoom: 0.95,
      },
      fog: {
        enabled: false,
        opacity: 0.9,
        style: 'white-mist',
        history: [],
      },
      grid: {
        enabled: true,
        type: 'square',
        size: 50,
        color: '#86efac',
        opacity: 0.25,
        offsetX: 0,
        offsetY: 0,
      },
      drawings: [],
      spellTemplates: [],
      animatedEffects: [
        {
          id: 'fx-river-water',
          position: { x: 0, y: 80 },
          radius: 200,
          type: 'water',
          intensity: 0.7,
          createdAt: Date.now(),
        },
      ],
      layersConfig: DEFAULT_LAYERS_CONFIG,
    },
  },
  {
    id: 'vault-preset-lich-crypt',
    name: '💀 Крипта Древнего Лича',
    category: 'Подземелья',
    description: 'Мрачный некротический мавзолей с саркофагами, пентаграммами, синим мистическим туманом и алтарем душ.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&q=80',
    previewColor: '#a855f7',
    tags: ['Лич', 'Подземелье', 'Крипта', 'Некромантия', 'Туман'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    isBuiltInPreset: true,
    stats: {
      propsCount: 1,
      hasFog: true,
      hasEffects: true,
      hasDrawings: false,
      hasSpells: true,
      bgWidth: 1500,
      bgHeight: 1100,
    },
    tabSnapshot: {
      id: 'tab-lich-crypt',
      name: '💀 Крипта Лича',
      icon: '💀',
      color: '#a855f7',
      notes: 'Филактерия спрятана в центральном саркофаге под защитой заклинания Круг Смерти.',
      createdAt: 1700000000000,
      updatedAt: 1700000000000,
      maps: [
        {
          id: 'map-bg-crypt',
          name: 'Главный Склеп Повелителя Теней',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1500&q=80',
          thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
          width: 1500,
          height: 1100,
          aspectRatio: 1500 / 1100,
          position: { x: -750, y: -550 },
          scale: { x: 1, y: 1 },
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          hash: 'hash-crypt-bg',
          fileSize: 890000,
          format: 'jpg',
          category: 'Подземелья',
          layer: 'background',
          locked: true,
        },
      ],
      activeMapId: 'map-bg-crypt',
      camera: {
        x: 0,
        y: 0,
        width: 1100,
        height: 618,
        rotation: 0,
        aspectRatio: 16 / 9,
        locked: false,
        zoom: 1,
      },
      fog: {
        enabled: true,
        opacity: 0.95,
        style: 'dark-obsidian',
        history: [
          { x: 0, y: 220, radius: 280, type: 'reveal' },
        ],
      },
      grid: {
        enabled: true,
        type: 'square',
        size: 50,
        color: '#c084fc',
        opacity: 0.3,
        offsetX: 0,
        offsetY: 0,
      },
      drawings: [],
      spellTemplates: [
        {
          id: 'spell-circle-death',
          type: 'circle',
          position: { x: 0, y: -120 },
          radius: 180,
          color: '#a855f7',
          label: 'Круг Смерти (Радиус 30 фт)',
          feetRadius: 30,
          angle: 0,
          effectType: 'necrotic',
          createdAt: Date.now(),
        },
      ],
      animatedEffects: [],
      layersConfig: DEFAULT_LAYERS_CONFIG,
    },
  },
];
